# <font color='blue'>Data Science Academy - Python Fundamentos - Capítulo 8</font>

## Download: http://github.com/dsacademybr

In [1]:
# Versão da Linguagem Python
from platform import python_version
print('Versão da Linguagem Python Usada Neste Jupyter Notebook:', python_version())

Versão da Linguagem Python Usada Neste Jupyter Notebook: 3.8.8


### Exercícios Sobre Módulos Python Para Análise de Dados

### ****** ATENÇÃO ******
### Alguns dos exercícios podem requerer pesquisa adicional na documentação dos pacotes. Pesquise!

### Exercício 1

In [8]:
# Crie um array NumPy com 1000000 e uma lista com 1000000.
# Multiplique cada elemento do array e da lista por 2 e calcule o tempo de execução com cada um dos objetos (use %time).
# Qual objeto oferece melhor performance, array NumPy ou lista?

import numpy as np
array_numpy = np.arange(1000000)
lista_python = list(range(1000000))

%time new_array_numpy = array_numpy * 2
%time new_lista_python1 = [x * 2 for x in lista_python]
%time new_lista_python3 = list(map(lambda x: x * 2, lista_python))

Wall time: 5 ms
Wall time: 165 ms
Wall time: 237 ms


### Exercício 2

In [6]:
# Exercício 2
# Crie um array de 10 elementos
# Altere o valores de todos os elementos dos índices 5 a 8 para 0

import numpy as np
array = np.arange(10)
array[5:8] = 0
array

array([0, 1, 2, 3, 4, 0, 0, 0, 8, 9])

### Exercício 3

In [17]:
# Crie um array de 3 dimensões e imprima a dimensão 1
import numpy as np
array_3d = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[10, 11, 12], [13, 14, 15], [16, 17, 18]]])
array_3d

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

### Exercício 4

In [28]:
# Crie um array de duas dimensões (matriz).
# Imprima os elementos da terceira linha da matriz
# Imprima todos os elementos da primeira e segunda linhas e segunda e terceira colunas

matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print('Primeira linha:\n',matrix[2])
print('Primeira e segunda linha e segunda e terceira colunas:\n',matrix[:2, 1:])

Primeira linha:
 [7 8 9]
Primeira e segunda linha e segunda e terceira colunas:
 [[2 3]
 [5 6]]


### Exercício 5

In [30]:
# Calcule a transposta da matriz abaixo
arr = np.arange(15).reshape((3, 5))
arr.transpose()

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

### Exercício 6

In [31]:
# Considere os 3 arrays abaixo
# Retorne o valor do array xarr se o valor for True no array cond. Caso contrário, retorne o valor do array yarr.
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

result = [*map(lambda x, y, c: x if c else y, xarr, yarr, cond)]
result

[1.1, 2.2, 1.3, 1.4, 2.5]

### Exercício 7

In [34]:
# Crie um array A com 10 elementos e salve o array em disco com a extensão npy
# Depois carregue o array do disco no array B

A = np.arange(10)
print(A)
np.save('array_A', A)

[0 1 2 3 4 5 6 7 8 9]


In [35]:
B = np.load('array_A.npy')
print(B)

[0 1 2 3 4 5 6 7 8 9]


### Exercício 8

In [38]:
# Considerando a série abaixo, imprima os valores únicos na série
import pandas as pd
obj = pd.Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c', 'a', 'b'])

print(obj.unique())

['c' 'a' 'd' 'b']


### Exercício 9

In [39]:
# Considerando o trecho de código que conecta em uma url na internet, imprima o dataframe conforme abaixo.
import requests
url = 'https://api.github.com/repos/pandas-dev/pandas/issues'
resp = requests.get(url)
resp

<Response [200]>

In [42]:
data = resp.json()
data[0]['title']

issues = pd.DataFrame(data, columns=['number', 'title', 'labels', 'state'])
issues

number                                              title  \
0    44763    BUG: Raise TypeError for scalar indexer in take   
1    44762  BUG: MultiIndex union setting wrong sortorder ...   
2    44761                  ENH: support SpooledTemporaryFile   
3    44758                                      PERF: unstack   
4    44757               DOC: Uniform block directive syntax.   
5    44755  BUG: reset_index on a MultiIndex with duplicat...   
6    44754    CI: CI / Web and docs fails more in last 2 days   
7    44752  BUG: UnsortedIndexError is raised when slicing...   
8    44751               Skew and kurtosis in describe method   
9    44748  BUG: pd.read_csv - encoding argument ignored f...   
10   44746                         ENH: IntervalArray.min/max   
11   44745  BUG: `pd.infer_freq` for quarterly with wrong ...   
12   44744                           CLN/TST: skips -> xfails   
13   44743  TST: do we still need tests.extension.arrow.ar...   
14   44742  API: extension tests BaseNoReduceTests/BaseBoo...   
15   44741                               TST: stricten xfails   
16   44740                       DOC: Fix swaplevel docstring   
17   44739  BUG: `swaplevel` docstring incorrectly indente...   
18   44738  PERF: reducing dtype checking overhead in groupby   
19   44736   [ArrayManager] Array version of interpolate l...   
20   44734          BUG: DF from parquet expands with groupby   
21   44732   CI: Flaky ResourceWarning: unclosedssl.SSLSocket   
22   44731                     CI: Run sdist build less often   
23   44726  BUG: split(expand=True) with boolean indexing ...   
24   44723  BUG: DataFrame.to_latex() does not correctly c...   
25   44722  ENH: allow JSON (de)serialization of Extension...   
26   44720  BUG: PeriodIndex does not survive JSON seriali...   
27   44718                 BUG: read sql from varbinary error   
28   44714  BUG: df.iloc[ndarray, ndarray] = 2dvals raisin...   
29   44712        ENH: Custom date boundaries for resamplers?   

                                               labels state  
0                                                  []  open  
1   [{'id': 2822098, 'node_id': 'MDU6TGFiZWwyODIyM...  open  
2   [{'id': 2301354, 'node_id': 'MDU6TGFiZWwyMzAxM...  open  
3   [{'id': 8935311, 'node_id': 'MDU6TGFiZWw4OTM1M...  open  
4   [{'id': 134699, 'node_id': 'MDU6TGFiZWwxMzQ2OT...  open  
5   [{'id': 71268330, 'node_id': 'MDU6TGFiZWw3MTI2...  open  
6                                                  []  open  
7   [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
8   [{'id': 76812, 'node_id': 'MDU6TGFiZWw3NjgxMg=...  open  
9   [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
10  [{'id': 76812, 'node_id': 'MDU6TGFiZWw3NjgxMg=...  open  
11  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
12  [{'id': 127685, 'node_id': 'MDU6TGFiZWwxMjc2OD...  open  
13  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
14  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
15  [{'id': 127685, 'node_id': 'MDU6TGFiZWwxMjc2OD...  open  
16  [{'id': 134699, 'node_id': 'MDU6TGFiZWwxMzQ2OT...  open  
17  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
18  [{'id': 8935311, 'node_id': 'MDU6TGFiZWw4OTM1M...  open  
19  [{'id': 2822342, 'node_id': 'MDU6TGFiZWwyODIyM...  open  
20  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
21  [{'id': 48070600, 'node_id': 'MDU6TGFiZWw0ODA3...  open  
22  [{'id': 129350, 'node_id': 'MDU6TGFiZWwxMjkzNT...  open  
23  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
24  [{'id': 251382258, 'node_id': 'MDU6TGFiZWwyNTE...  open  
25  [{'id': 76812, 'node_id': 'MDU6TGFiZWw3NjgxMg=...  open  
26  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
27  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
28                                                 []  open  
29  [{'id': 76812, 'node_id': 'MDU6TGFiZWw3NjgxMg=...  open

### Exercício 10

In [44]:
# Crie um banco de dados no SQLite, crie uma tabela, insira registros, 
# consulte a tabela e retorne os dados em dataframe do Pandas

import sqlite3
import pandas as pd
query = """
CREATE TABLE EQUIPAMENTO
(Tipo VARCHAR(20), 
 Cidade VARCHAR(30),
 Numero INTEGER,        
 Subestacao VARCHAR(4),
 Alimentador INTEGER
);"""
con = sqlite3.connect('dsa.db')
con.execute(query)
con.commit()

In [47]:
data = [('Religador', 'Sao D. do Prata', 289510, 'PRTU', 101),
        ('Transformador', 'Teofilo Otoni', 1515, 'TOTU', 112),
        ('Seccionalizador', 'Barao de Cocais', 1234, 'BCSQ', 419),
        ('Regulador de tensao', 'Joao Monlevade', 808, 'JMLT', 316)]
stmt = "INSERT INTO EQUIPAMENTO VALUES(?, ?, ?, ?, ?)"
con.executemany(stmt, data)
con.commit()

In [48]:
cursor = con.execute('select * from EQUIPAMENTO')
rows = cursor.fetchall()
rows

[('Religador', 'Sao D. do Prata', 289510, 'PRTU', 101),
 ('Transformador', 'Teofilo Otoni', 1515, 'TOTU', 112),
 ('Seccionalizador', 'Barao de Cocais', 1234, 'BCSQ', 419),
 ('Regulador de tensao', 'Joao Monlevade', 808, 'JMLT', 316)]

In [49]:
cursor.description
pd.DataFrame(rows, columns=[x[0] for x in cursor.description])

Tipo           Cidade  Numero Subestacao  Alimentador
0            Religador  Sao D. do Prata  289510       PRTU          101
1        Transformador    Teofilo Otoni    1515       TOTU          112
2      Seccionalizador  Barao de Cocais    1234       BCSQ          419
3  Regulador de tensao   Joao Monlevade     808       JMLT          316

# Fim


### Obrigado

### Visite o Blog da Data Science Academy - <a href="http://blog.dsacademy.com.br">Blog DSA</a>
